### ISSUE TITLE
New feature suggestion

### ISSUE THREAD

**Issue by Hessutar** [timothyrichards/ScarletUI#1]
Hopefully this is the right ScarletUI from CurseForge :) Couldn't post my comment there so I found this from Google.

Hello! Found your addon a few weeks a go and have been really liking it! This hits just the perfect spot on keeping and adjusting the default UI. 

Do you have a discord/github page to suggest new features? Maybe you could add this github page to the addon description? 

The only thing I've been missing is a way to show buffs/debuffs and combopoints on nameplates. Would it be possible to implement something like this and perhaps have a filter to adjust source/whitelist/blacklist of the buffs/debuffs to show on nameplates?

**Comment by Hessutar** [comment]
Would it also be possible to add these raidframe frame width/height to be configurable in game addon settings?

![image](https://github.com/timothyrichards/ScarletUI/assets/5693510/2de378d5-2598-4c64-8613-146d56c3becf)

PS. Still unable to comment at CurseForge to your addon's page.

**Comment by timothyrichards** [comment]
> The only thing I've been missing is a way to show buffs/debuffs and combopoints on nameplates. Would it be possible to implement something like this and perhaps have a filter to adjust source/whitelist/blacklist of the buffs/debuffs to show on nameplates?

Currently I personally use a weakaura for showing the buffs and debuffs, but this is something that I have had in consideration, I'm just not fully sure how to properly implement it in a way that will be easy to use and understand yet, the first iteration will probably default to only showing personal debuffs, and expand from there

> Would it also be possible to add these raidframe frame width/height to be configurable in game addon settings?
> 
> ![image](https://private-user-images.githubusercontent.com/5693510/285129486-2de378d5-2598-4c64-8613-146d56c3becf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExMjkzNDcsIm5iZiI6MTcwMTEyOTA0NywicGF0aCI6Ii81NjkzNTEwLzI4NTEyOTQ4Ni0yZGUzNzhkNS0yNTk4LTRjNjQtODYxMy0xNDZkNTZjM2JlY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMjM1MDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzEwM2Y1YTE5MjI5Njg1Y2E0M2I5YWQwZjEzZWMxZmI5NGZiMzVmMTY3NzI5NjkxZWZlZTczNzExOWMwMmIzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._mTJFcTmmGEzpm4nxRzwYnP_fFaM1pTHwpfaacOzlvw)

Recently I made an adjustment to how you could move and resize the raid/party frames, allowing the user to adjust them via the default UI and then capture the new settings and save it to the addon, I'm considering doing something similar to that with the interface options that allow you to change profile settings, then just having those settings get updated on your other characters when you login.

Otherwise I would need to recreate the entire settings page for raid frames and make sure it always has the same options as the base UI, which is a lot more effort.

Do you think that would be an acceptable middle ground?

**Comment by Hessutar** [comment]
Heya! Yes that sounds very reasonable. Getting rest of the interface options saved to the addon as well would be glorius. The best feature I enjoy about your addon, is that I need to setup my UI once and all will be set for all my characters. 

Do you have a guide how to capture the default ui raid frame settings to the addon? 

Also only showing your own debuffs on the target is pretty much how I use any nameplate addon. One could always get BigDebuffs or something else to show important cc on the nameplates.

**Comment by timothyrichards** [comment]
> Heya! Yes that sounds very reasonable. Getting rest of the interface options saved to the addon as well would be glorius. The best feature I enjoy about your addon, is that I need to setup my UI once and all will be set for all my characters.
> 
> Do you have a guide how to capture the default ui raid frame settings to the addon?

Not currently, it's actually not capturing any values at all, only setting hard set values (the ones you referenced)

> Also only showing your own debuffs on the target is pretty much how I use any nameplate addon. One could always get BigDebuffs or something else to show important cc on the nameplates.

I would probably want to expand it to also optionally include seeing things like Sunder or Expose Armor, etc... Things that other ppl apply that would matter to you as well.

**Comment by timothyrichards** [comment]
Hey @Hessutar,

Forgot to follow up on this, I added the ability for the addon to store and load all of the raid frame profile settings in this commit: https://github.com/timothyrichards/ScarletUI/commit/bb78a85e5f5cf44547a8962dc0f65df2428ae5c0

So now when you're in game, if you change any interface > raid frames settings, you should see those changes persist between reloads/play sessions, as well as be replicated to your other characters.

This will only apply to the two profiles created by the addon though, Party and Raid.

If you run into any issues let me know!

I'm still trying to figure out the best way to implement the nameplate related changes you requested, adding features to base nameplates is quite tricky it turns out.

**Comment by Hessutar** [comment]
Nice! I'll check it out.

-Hessutar

**Comment by timothyrichards** [comment]
Got another update for you @Hessutar,

In this commit: https://github.com/timothyrichards/ScarletUI/commit/892c9c41243a2b06e7a71935860b681e5fc226cc

Debuffs have been added to the nameplates, I don't have any filters available at the moment.

If you would like the filter feature would you be willing to create a new issue requesting that feature so I can track it separately from this one?

**Comment by Hessutar** [comment]
Nice one! Yeh I’ll check it out and make a new issue If a filter is needeed :) 

-Hessutar
